// This file was generated by counterfeiter
package voldriverfakes

import (
	"context"
	"sync"

	"code.cloudfoundry.org/lager"
	"code.cloudfoundry.org/voldriver"
)

type FakeEnv struct {
	LoggerStub        func() *lager.Logger
	loggerMutex       sync.RWMutex
	loggerArgsForCall []struct{}
	loggerReturns     struct {
		result1 *lager.Logger
	}
	ContextStub        func() *context.Context
	contextMutex       sync.RWMutex
	contextArgsForCall []struct{}
	contextReturns     struct {
		result1 *context.Context
	}
	WithLoggerStub        func(logger *lager.Logger)
	withLoggerMutex       sync.RWMutex
	withLoggerArgsForCall []struct {
		logger *lager.Logger
	}
	WithContextStub        func(ctx *context.Context)
	withContextMutex       sync.RWMutex
	withContextArgsForCall []struct {
		ctx *context.Context
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeEnv) Logger() *lager.Logger {
	fake.loggerMutex.Lock()
	fake.loggerArgsForCall = append(fake.loggerArgsForCall, struct{}{})
	fake.recordInvocation("Logger", []interface{}{})
	fake.loggerMutex.Unlock()
	if fake.LoggerStub != nil {
		return fake.LoggerStub()
	} else {
		return fake.loggerReturns.result1
	}
}

func (fake *FakeEnv) LoggerCallCount() int {
	fake.loggerMutex.RLock()
	defer fake.loggerMutex.RUnlock()
	return len(fake.loggerArgsForCall)
}

func (fake *FakeEnv) LoggerReturns(result1 *lager.Logger) {
	fake.LoggerStub = nil
	fake.loggerReturns = struct {
		result1 *lager.Logger
	}{result1}
}

func (fake *FakeEnv) Context() *context.Context {
	fake.contextMutex.Lock()
	fake.contextArgsForCall = append(fake.contextArgsForCall, struct{}{})
	fake.recordInvocation("Context", []interface{}{})
	fake.contextMutex.Unlock()
	if fake.ContextStub != nil {
		return fake.ContextStub()
	} else {
		return fake.contextReturns.result1
	}
}

func (fake *FakeEnv) ContextCallCount() int {
	fake.contextMutex.RLock()
	defer fake.contextMutex.RUnlock()
	return len(fake.contextArgsForCall)
}

func (fake *FakeEnv) ContextReturns(result1 *context.Context) {
	fake.ContextStub = nil
	fake.contextReturns = struct {
		result1 *context.Context
	}{result1}
}

func (fake *FakeEnv) WithLogger(logger *lager.Logger) {
	fake.withLoggerMutex.Lock()
	fake.withLoggerArgsForCall = append(fake.withLoggerArgsForCall, struct {
		logger *lager.Logger
	}{logger})
	fake.recordInvocation("WithLogger", []interface{}{logger})
	fake.withLoggerMutex.Unlock()
	if fake.WithLoggerStub != nil {
		fake.WithLoggerStub(logger)
	}
}

func (fake *FakeEnv) WithLoggerCallCount() int {
	fake.withLoggerMutex.RLock()
	defer fake.withLoggerMutex.RUnlock()
	return len(fake.withLoggerArgsForCall)
}

func (fake *FakeEnv) WithLoggerArgsForCall(i int) *lager.Logger {
	fake.withLoggerMutex.RLock()
	defer fake.withLoggerMutex.RUnlock()
	return fake.withLoggerArgsForCall[i].logger
}

func (fake *FakeEnv) WithContext(ctx *context.Context) {
	fake.withContextMutex.Lock()
	fake.withContextArgsForCall = append(fake.withContextArgsForCall, struct {
		ctx *context.Context
	}{ctx})
	fake.recordInvocation("WithContext", []interface{}{ctx})
	fake.withContextMutex.Unlock()
	if fake.WithContextStub != nil {
		fake.WithContextStub(ctx)
	}
}

func (fake *FakeEnv) WithContextCallCount() int {
	fake.withContextMutex.RLock()
	defer fake.withContextMutex.RUnlock()
	return len(fake.withContextArgsForCall)
}

func (fake *FakeEnv) WithContextArgsForCall(i int) *context.Context {
	fake.withContextMutex.RLock()
	defer fake.withContextMutex.RUnlock()
	return fake.withContextArgsForCall[i].ctx
}

func (fake *FakeEnv) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.loggerMutex.RLock()
	defer fake.loggerMutex.RUnlock()
	fake.contextMutex.RLock()
	defer fake.contextMutex.RUnlock()
	fake.withLoggerMutex.RLock()
	defer fake.withLoggerMutex.RUnlock()
	fake.withContextMutex.RLock()
	defer fake.withContextMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeEnv) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ voldriver.Env = new(FakeEnv)
